### Assessing the Projections at Betting Pros.com

<img src="images/Props.png" width="800" height="400">


We are assessing the projections betting pros has on their website. In the drop-down menu, if we choose `Points Over/Under`, we get the day's player props, along with different offerings from different sportsbooks. For example, the over/under for Jrue Holiday on tonight's points opened at $14.5$, with a slight tilt in the *under* direction, at $-118$ odds compared to $-108$ for the over.

<img src="images/Holiday.png" width="1000" height="600">

The site also has the *best* column, which represents the best price you can get among the sportsbooks featured on their site (BetMGM, DKNG, Fanduel, Prizepicks, Caesars and more). If you dig in the underlying API (see [here, for example](https://api.bettingpros.com/v3/pbcs?sport=NBA&location=CA&book_id=37%3A36&event_id=25044). You may need to start a session), you will find a `Projection` column, which we think is the site's own projection, but we cannot find it when looking at the page in a web browser.

In [1]:
import pandas as pd
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)
pd.options.display.width = 0
pd.options.display.max_colwidth = 100

In [2]:
df = pd.read_csv("BETTINGPROS.csv", index_col = 0)

In [3]:
df.head()

,SEASON_YEAR,PLAYER_NAME,TEAM_ABBREVIATION,GAME_DATE,MATCHUP,home_away,OPP,MIN_PLAYER,FGM_PLAYER,FGA_PLAYER,FG_PCT_PLAYER,FG3M_PLAYER,FG3A_PLAYER,FG3_PCT_PLAYER,FTM_PLAYER,FTA_PLAYER,FT_PCT_PLAYER,OREB_PLAYER,DREB_PLAYER,REB_PLAYER,AST_PLAYER,TOV_PLAYER,STL_PLAYER,BLK_PLAYER,BLKA_PLAYER,PF_PLAYER,PFD_PLAYER,PTS_PLAYER,PLUS_MINUS_PLAYER,DD2,TD3,WL_TEAM,MIN_TEAM,FGM_TEAM,FGA_TEAM,FG_PCT_TEAM,FG3M_TEAM,FG3A_TEAM,FG3_PCT_TEAM,FTM_TEAM,FTA_TEAM,FT_PCT_TEAM,OREB_TEAM,DREB_TEAM,REB_TEAM,AST_TEAM,TOV_TEAM,STL_TEAM,BLK_TEAM,BLKA_TEAM,PF_TEAM,PFD_TEAM,PTS_TEAM,PLUS_MINUS_TEAM,TEAM_ID_OPP,WL_OPP,MIN_OPP,FGM_OPP,FGA_OPP,FG_PCT_OPP,FG3M_OPP,FG3A_OPP,FG3_PCT_OPP,FTM_OPP,FTA_OPP,FT_PCT_OPP,OREB_OPP,DREB_OPP,REB_OPP,AST_OPP,TOV_OPP,STL_OPP,BLK_OPP,BLKA_OPP,PF_OPP,PFD_OPP,PTS_OPP,PLUS_MINUS_OPP,days_rest,rolling_avg,rolling_3PA_avg,mpg_rolling,rolling_team_fta,rolling_opp_pts,Market_ID,Market_Full_Label,Participant_ID,Participant_Name,Cost,Consensus_Cost,Cost_Inverse,Projection,Recommendation,Line,Consensus,Actual,is_over_rec,rec_DIFF,outcome_DIFF,hundred_rec
0,2022-23,John Collins,ATL,2023-01-02,ATL @ GSW,@,GSW,39.640000,9,17,0.529,1,5,0.200,6,8,0.750,2,11,13,1,2,1,2,1,4,5,25,-2,1,0,L,58.0,53,109,0.486,11,35,0.314,24,29,0.828,10,43,53,30,13.0,9,10,6,17,23,141,-2.0,1610612744,W,58.0,54,121,0.446,19,59,0.322,16,24,0.667,23,46,69,34,19.0,9,6,10,23,17,143,2.0,3 days,13.2,3.0,27.321333,22.2,116.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,0.000000
1,2022-23,Trae Young,ATL,2023-01-02,ATL @ GSW,@,GSW,43.523333,8,22,0.364,3,10,0.300,11,13,0.846,1,6,7,14,4,1,0,1,2,7,30,-8,1,0,L,58.0,53,109,0.486,11,35,0.314,24,29,0.828,10,43,53,30,13.0,9,10,6,17,23,141,-2.0,1610612744,W,58.0,54,121,0.446,19,59,0.322,16,24,0.667,23,46,69,34,19.0,9,6,10,23,17,143,2.0,3 days,29.6,7.6,35.142667,21.8,119.8,157.0,Rebounds,3473.0,Trae Young,-164.0,-175.0,-150.0,3.9,over,2.5,2.5,7.0,True,1.4,4.5,60.975610
2,2022-23,Trae Young,ATL,2023-01-02,ATL @ GSW,@,GSW,43.523333,8,22,0.364,3,10,0.300,11,13,0.846,1,6,7,14,4,1,0,1,2,7,30,-8,1,0,L,58.0,53,109,0.486,11,35,0.314,24,29,0.828,10,43,53,30,13.0,9,10,6,17,23,141,-2.0,1610612744,W,58.0,54,121,0.446,19,59,0.322,16,24,0.667,23,46,69,34,19.0,9,6,10,23,17,143,2.0,3 days,29.6,7.6,35.142667,21.8,119.8,151.0,Assists,3473.0,Trae Young,-108.0,-115.0,110.0,10.5,over,9.5,9.5,14.0,True,1.0,4.5,92.592593
3,2022-23,De'Andre Hunter,ATL,2023-01-02,ATL @ GSW,@,GSW,38.083333,6,13,0.462,2,6,0.333,3,4,0.750,0,4,4,2,0,2,2,1,3,6,17,-3,0,0,L,58.0,53,109,0.486,11,35,0.314,24,29,0.828,10,43,53,30,13.0,9,10,6,17,23,141,-2.0,1610612744,W,58.0,54,121,0.446,19,59,0.322,16,24,0.667,23,46,69,34,19.0,9,6,10,23,17,143,2.0,10 days,14.2,5.0,33.064667,24.2,116.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,0.000000
4,2022-23,Aaron Holiday,ATL,2023-01-02,ATL @ GSW,@,GSW,15.593333,2,4,0.500,1,2,0.500,0,0,0.000,0,2,2,1,0,0,1,0,0,0,5,6,0,0,L,58.0,53,109,0.486,11,35,0.314,24,29,0.828,10,43,53,30,13.0,9,10,6,17,23,141,-2.0,1610612744,W,58.0,54,121,0.446,19,59,0.322,16,24,0.667,23,46,69,34,19.0,9,6,10,23,17,143,2.0,3 days,3.2,1.4,12.502333,22.2,116.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,0.000000

### Description of Columns

We have merged the data with data from the [nba_api](https://github.com/swar/nba_api), a very useful python wrapper for stats.nba.com that has a decent community slack channel. Here is a description of some of the merged columns.

- `Market_Full_Label` - Points, Rebounds, or Assists
- `Projection` - the site's own projected outcome.
- `Recommendation` - the site's recommendation (*over*/*under*) based on the difference between `Projection` and `Line`
- `rec_DIFF` - the difference between `Projection` and `Line`
- `Actual` - the actual outcome.
- `outcome_DIFF` - the difference between `Actual` and `Line`
- `hundred_rec` - profit (positive or negative) from a hundred dollar that follows the `Recommendation` column.

  The rest of the columns are stats. Stat names that are appended with `_PLAYER`, `_TEAM`, or `_OPP`. IE in the first row, John Collins had $2$ blocks, his team had $10$ total blocks, and the opposing team had $6$ total blocks.

In [4]:
df.loc[:,['SEASON_YEAR','PLAYER_NAME','BLK_PLAYER','BLK_TEAM','BLK_OPP']].head()

  SEASON_YEAR      PLAYER_NAME  BLK_PLAYER  BLK_TEAM  BLK_OPP
0     2022-23     John Collins           2        10        6
1     2022-23       Trae Young           0        10        6
2     2022-23       Trae Young           0        10        6
3     2022-23  De'Andre Hunter           2        10        6
4     2022-23    Aaron Holiday           1        10        6

What we want to compare is how well the `Projection` column performs on the data.

In [5]:
df.groupby(['Recommendation','Market_Full_Label'])['hundred_rec'].agg(['count','mean'])

                                  count      mean
Recommendation Market_Full_Label
over           Assists            14821 -1.779385
               Points             15836 -5.063682
               Rebounds           15207 -2.804901
under          Assists             8443 -1.440146
               Points              8614  2.211831
               Rebounds            8659  5.806240

From this result, we see that the recommendations seem to be good for the **Points** and **Rebounds** whenever the recommendation is *under*, but NOT if the recommendation is *over* (The average ROI is $5.8$% on a Rebounds prop bet if the recommendation is *under*, and $-2.8$% if the recommendation is *over*).

In [20]:
df.groupby('Recommendation')['hundred_rec'].agg(['count','mean'])

                count      mean
Recommendation
over            45864 -3.253420
under           25716  2.223122

Overall, it seems that the **Recommendation** is only good when it is under.

In [6]:
df.groupby(['Recommendation','Market_Full_Label','SEASON_YEAR'])['hundred_rec'].agg(['count','mean'])

                                              count      mean
Recommendation Market_Full_Label SEASON_YEAR
over           Assists           2022-23       7163 -1.707626
                                 2023-24       7658 -1.846506
               Points            2022-23       7219 -5.347359
                                 2023-24       8617 -4.826027
               Rebounds          2022-23       7420 -2.624309
                                 2023-24       7787 -2.976981
under          Assists           2022-23       3490 -0.301931
                                 2023-24       4953 -2.242160
               Points            2022-23       3798  0.819611
                                 2023-24       4816  3.309766
               Rebounds          2022-23       3341  7.353076
                                 2023-24       5318  4.834450

Now we want to see if we should be *more confident* in a *projection* with a larger gap than a smaller one. To do this, we can use **pd.cut**.

In [60]:
df['diff_bins'] = pd.cut(df['rec_DIFF'], bins = [-10,-3.8,-3.1,-2.5,-0.8,0,1.1,3.1,10])

In [61]:
POINTS = df[df['Market_Full_Label'] == 'Points']
POINTS.groupby('diff_bins')['hundred_rec'].agg(['count','mean'])

               count      mean
diff_bins
(-10.0, -3.8]    325  6.707309
(-3.8, -3.1]     423  4.114039
(-3.1, -2.5]     783  5.702861
(-2.5, -0.8]    4426  1.306102
(-0.8, 0.0]     2656  1.828540
(0.0, 1.1]      4940 -5.008811
(1.1, 3.1]      8914 -5.553689
(3.1, 10.0]     1981 -3.047168

As you can see with the **Points** prop bets, an **UNDER** recommendation is better when there is a large difference between the **Projection** column and the actual **Line**. However, an **OVER** recommendation is never good. The average ROI on a $100\$$ wager when there is a $-3.8$ point difference or less is $6.70\$$.

In [65]:
df['diff_bins'] = pd.cut(df['rec_DIFF'], bins = [-10,-2.0,-1.1,0,1.1,3.1,10])
REBOUNDS = df[df['Market_Full_Label'] == 'Rebounds']
REBOUNDS.groupby('diff_bins')['hundred_rec'].agg(['count','mean'])

               count       mean
diff_bins
(-10.0, -2.0]    164  16.018819
(-2.0, -1.1]    1171   8.075406
(-1.1, 0.0]     7324   5.214752
(0.0, 1.1]     11978  -2.995628
(1.1, 3.1]      3213  -2.093761
(3.1, 10.0]       16  -2.827758

For Rebounds, the same trend is present; the strategy says *bet the UNDER* if the Betting Pros projection says so, and bet multiple units if the projection differs from the Line by $2$ rebounds or more. The strategy also says *never bet the OVER*.

### Conclusion

Further analysis should include

- data validation
- incorporating other statistics to find more trends